apiVersion: v1
kind: Service
metadata:
  name: svc-f 
spec:
  selector:
    app: fnginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fnginx
  template:
    metadata:
      name: f-pod
      labels:
        app: fnginx
    spec:
      containers:
      - name: web-con
        image: onineraz/front:3
